package com.thegutuproject.pizzashop.db.model;

import java.io.Serializable;

public class OrderLogDb implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_log.ORDER_LOG_ID
     *
     * @mbg.generated Mon Mar 12 12:31:13 EDT 2018
     */
    private Integer orderLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_log
     *
     * @mbg.generated Mon Mar 12 12:31:13 EDT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_log.ORDER_LOG_ID
     *
     * @return the value of order_log.ORDER_LOG_ID
     *
     * @mbg.generated Mon Mar 12 12:31:13 EDT 2018
     */
    public Integer getOrderLogId() {
        return orderLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_log.ORDER_LOG_ID
     *
     * @param orderLogId the value for order_log.ORDER_LOG_ID
     *
     * @mbg.generated Mon Mar 12 12:31:13 EDT 2018
     */
    public void setOrderLogId(Integer orderLogId) {
        this.orderLogId = orderLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Mon Mar 12 12:31:13 EDT 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderLogDb other = (OrderLogDb) that;
        return (this.getOrderLogId() == null ? other.getOrderLogId() == null : this.getOrderLogId().equals(other.getOrderLogId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Mon Mar 12 12:31:13 EDT 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderLogId() == null) ? 0 : getOrderLogId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Mon Mar 12 12:31:13 EDT 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderLogId=").append(orderLogId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}