package com.thegutuproject.pizzashop.db.mapper;

import com.thegutuproject.pizzashop.db.model.OrderLogDb;
import com.thegutuproject.pizzashop.db.model.OrderLogDbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderLogDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    long countByExample(OrderLogDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    int deleteByExample(OrderLogDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    int deleteByPrimaryKey(Integer orderLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    int insert(OrderLogDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    int insertSelective(OrderLogDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    List<OrderLogDb> selectByExampleWithRowbounds(OrderLogDbExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    List<OrderLogDb> selectByExample(OrderLogDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    int updateByExampleSelective(@Param("record") OrderLogDb record, @Param("example") OrderLogDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_log
     *
     * @mbg.generated Tue Mar 13 14:55:23 EDT 2018
     */
    int updateByExample(@Param("record") OrderLogDb record, @Param("example") OrderLogDbExample example);
}